# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "MESSAGES" ("ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"NAME" VARCHAR NOT NULL,"MAIL" VARCHAR NOT NULL,"MESSAGE" VARCHAR NOT NULL,"POSTDATE" TIMESTAMP NOT NULL);

# --- !Downs

drop table "MESSAGES";

